export const items=[{item:"Delux Chicken Tandoori Full",price:280},
            {item:"Delux Chicken Tandoori Half",price:160},
            {item:"Chicken Pahadi 6 Pcs",price:160},
            {item:"Chicken Tikka 6 Pcs",price:150},
            {item:"Chicken Reshami Tikka 6 Pcs",price:160},
            {item:"Chicken Tandoori Lolipop 6 Pcs",price:170},
            {item:"Chicken Malai Tikka 6 Pcs",price:220},
            {item:"Chicken Anagara Kabab 6 Pcs",price:160},
            {item:"Chicken Dilkhush Kabab (Chees Feeling)",price:180},
            {item:"Chicken Chatpata Kabab 6 Pcs",price:160},
            {item:"Chicken Achari Tikka 6 Pcs",price:170},
            {item:"Chicken Banjara Kabab 6 Pcs",price:170},
            {item:"Chicken Hydrabadi Kabab 6 Pcs",price:190},
            {item:"Chicken Tiranga Kababa 12 Pcs",price:300},
            {item:"Chicken Seekh Kabab 6 Pcs",price:220},
            {item:"Chicken Boti Kabab 6 Pcs",price:200},
            {item:"Murg Rozali Kabab 6 Pcs (Breast Stuff With Chees)",price:230},
            {item:"Chicken Kalmi Kabab 6pc",price:160},
            {item:"Chicken Sholay Kabab",price:260},
            {item:"Kalimirch Murg Tikka 6pcs",price:180},
            {item:"Chicken Tangadi Kabab 2 Pcs",price:200},
            {item:"Chicken Pakoda 8 Pcs",price:120},
            {item:"Chicken Platter",price:800},
            {item:"Chicken Sukha",price:150},                                 /*"Non-Veg Gravy & Dry"*/
            {item:"Chicken Masala",price:150},
            {item:"Butter Chkn Boneless",price:170},
            {item:"Chicken Kolhapuri Boneless",price:160},
            {item:"Chicken Handi Boneless",price:160},
            {item:"Chicken Kadai",price:160},
            {item:"Chicken Hydrabadi Boneless",price:160},
            {item:"Chicken Tikka Masala Boneless",price:160},
            {item:"Chicken Pahadi Tikka Masala",price:170},
            {item:"Chicken Seekh Masala",price:170},
            {item:"Chicken Afghani Boneless",price:170},
            {item:"Chicken Mughlai",price:170},
            {item:"Chicken Patiala",price:170},
            {item:"Chicken Achari",price:170},
            {item:"Chicken Curry",price:140},
            {item:"Chicken Rogan Josh",price:150},
            {item:"Chicken Tiranga",price:200},
            {item:"Chicken Rara",price:170},
            {item:"Chicken Bhuna Masala",price:160},
            {item:"Chicken Lajawab",price:170},
            {item:"Chicken Do Pyaza",price:170},
            {item:"Special Matka Murg Masallam",price:320},
            {item:"Chicken Chingari",price:190},
            {item:"Chicken Mumtaz Boneless",price:190},
            {item:"Chicken Angara",price:180},
            {item:"Italian Pasta",price:160},                                                 /*  Contiental cousine  */                 
            {item:"Roasted Veggies Pasta",price:160},
            {item:"Mashroom Pasta",price:160},
            {item:"Baby Corn Cheese Pasta",price:160},
            {item:"Margarita Pasta",price:150},
            {item:"Chicken Italian Pasta",price:180},
            {item:"Chicken Pesto Pasta",price:180},
            {item:"Chicken Cheese Alfredo Sauce Pasta",price:180},
            {item:"Chicken Cilantro Pasta",price:180},
            {item:"Chicken Creamy Pasta",price:180},
            {item:"Chicken Salami Pasta",price:180},
            {item:"Chicken Red Sauce Arabbiata Pasta",price:180},
            {item:"Avacado Toast Sandwich",price:180},                                               /*   SANDWITCH */
            {item:"Veg Club Sandwich",price:150},
            {item:"Avacado Sandwich",price:160},
            {item:"Roasted Veggies Sandwich",price:150},
            {item:"Onion Potato Sandwich",price:150},
            {item:"Contiental Bucket Sandwich",price:150},
            {item:"Corn Chees Sandwich",price:160},
            {item:"Falafel Sandwich",price:160},
            {item:"Egg And Avacado Sandwich",price:160},
            {item:"Egg Mashroom And Chees",price:165},
            {item:"Egg Chicken And Chees",price:150},
            {item:"Mayo Grilled Chicken Sandwich",price:160},
            {item:"Chicken Salami Sandwich",price:170},
            {item:"Worm Grain Bowl",price:210},                       /*FreshBowl*/
            {item:"Worm Grain Bowl Grilled Chicken",price:250},
            {item:"Worm Grain Bowl Chicken Thai",price:250},
            {item:"Falafel Bowl",price:210},
            {item:"Falafel Bowl Grilled Chicken",price:250},
            {item:"Chicken Quinoa Bowl",price:250},
            {item:"Chipotle Chicken Bowl",price:250},
            {item:"Paneer Tikka 6 Pcs",price:150},                    /*Veg Starter */
            {item:"Paneer Pudina 6 Pcs",price:160},
            {item:"Paneer Schezwan Tikka 6 Pcs",price:160},
            {item:"Paneer Malai Tikka 6 Pcs",price:170},
            {item:"Paneer Hilltop Tikka",price:180},
            {item:"Paneer Achari Tikka",price:160},
            {item:"Paneer Pahadi Kabab",price:170},
            {item:"Paneer Pakoda 8 pcs",price:110},
            {item:"Veg Seekh Kabab",price:120},
            {item:"Veg Lajwab",price:150},
            {item:"Veg Banarasi",price:160},
            {item:"Ek Full Do Mali",price:180},
            {item:"Cheez Pakoda 8 Pcs",price:130},
            {item:"Veg Chees Ball 8 Pcs",price:100},
            {item:"Babycorn Tandoori",price:130},
            {item:"Mashroom Tandoori Kabab 8 Pcs",price:130},
            {item:"Paneer Butter Masala",price:140},                  /*Veg Gravy and Dry*/
            {item:"Paneer Masala",price:120},
            {item:"Paneer Palak",price:120},
            {item:"Paneer Mutter",price:120},
            {item:"Paneer Kolhapuri",price:120},
            {item:"Paneer Khurma",price:150},
            {item:"Paneer Kofta",price:160},
            {item:"Paneer Bhurji",price:170},
            {item:"Paneer Chili Mill",price:160},
            {item:"Paneer Kadai",price:140},
            {item:"Paneer Jaypuri",price:140},
            {item:"Paneer Malwani",price:130},
            {item:"Paneer Tiranga",price:190},
            {item:"Paneer Tava",price:170},
            {item:"Paneer Do Pyaza",price:180},
            {item:"Paneer Handi",price:130},
            {item:"Alu Mutter",price:100},
            {item:"Alu Palak",price:100},
            {item:"Veg Kolhapuri",price:130},
            {item:"Veg Kofta",price:120},
            {item:"Veg Hydrabadi",price:100},
            {item:"Veg Maratha",price:140},
            {item:"Veg Malwani",price:120},
            {item:"Veg Tava",price:150},
            {item:"Veg Jaypuri",price:130},
            {item:"Chole Masala",price:100},
            {item:"Dal Butter Fry",price:100},
            {item:"Dal Tadka",price:100},
            {item:"Dal Fry",price:90},
            {item:"Dal Khichadi Special With Raitai",price:150},
            {item:"Yellow Protein Pot",price:210},                 /*Healthy Protien Pot*/
            {item:"Red Protein Pot",price:210},
            {item:"Green Protein Pot",price:210},
            {item:"Quinoa Tabbouleh",price:210},
            {item:"Chicken Pesto Pot",price:210},
            {item:"Greek Salad",price:290},                       /*Salad*/
            {item:"Chicken Caesar Salad",price:300},
            {item:"Roasted Veggies",price:290},
            {item:"Chicken Pesto Pot",price:280},
            {item:"Pink Smoothies Bowl",price:220},                /*Smoothies Bowl*/
            {item:"Green Smoothies Bowl",price:220},
            {item:"Mango Chia Puding",price:160},                  /*Dessert*/
            {item:"Berry Chia Puding",price:160},
            {item:"Chocolate Chips Cookie",price:160},
            {item:"Red Valvet Cookie",price:160},
            {item:"Brownie With Vanilla Icecream",price:160},
            {item:"Steamed Rice",price:70},                      /*Veg Rice*/
            {item:"Jira Rice",price:90},
            {item:"Biryani Rice",price:100},
            {item:"Veg Biryani",price:110},
            {item:"Veg Pulao",price:110},
            {item:"Veg Tava Pulao",price:120},
            {item:"Paneer Tikka Biryani",price:130},
            {item:"Paneer Pulao",price:120},
            {item:"Paneer Tava Pulao",price:130},
            {item:"Hydrabadi Biryani",price:130},
            {item:"Chicken Tikka Biryani",price:140},              /*Non-Veg Biryani*/
            {item:"Chicken Biryani",price:120},
            {item:"Chicken Hydrabadi Biryani",price:130},
            {item:"Chicken Bonless Biryani",price:150},
            {item:"Chicken Tandoori Biryani",price:150},
            {item:"Chicken Tava Biryani",price:130},
            {item:"Chicken Tava Pulao",price:140},
            {item:"Chicken Pulao",price:120},
            {item:"Veg Chilli 10 Pcs",price:110},                 /*Chinese Starter Veg*/
            {item:"Veg Manchurian",price:130},
            {item:"Veg Crispy",price:140},
            {item:"Soyabean Chilli",price:130},
            {item:"Paneer Crispy",price:150},
            {item:"Paneer Chilli",price:140},
            {item:"Paneer Manchurian",price:140},
            {item:"Paneer Schezwan",price:140},
            {item:"Mashroom Chilli",price:140},
            {item:"Mashroom Schezwan",price:140},
            {item:"Veg Manchow Soup",price:80},
            {item:"Veg Hot & Sour Soup",price:80},
            {item:"Veg Clear Soup",price:70},
            {item:"Cream of Mashroom",price:100},
            {item:"Cream of Tomato",price:100},
            {item:"Cream of Palak",price:100},
            {item:"Chicken Manchow Soup",price:110},                  /*Non-Veg Soup*/
            {item:"Chicken Clear Soup",price:100},
            {item:"Chicken Hot & Sour",price:120},
            {item:"Chicken Lungfung Soup",price:130},
            {item:"Tandoori Roti",price:15},                         /*Naan /Roti/Paratha*/
            {item:"Tandoori Butter Roti",price:20},
            {item:"Tandoori Butter Naan",price:35},
            {item:"Tandoori Naan",price:25},
            {item:"Tandoori Butter Paratha",price:30},
            {item:"Tandoori Stuffed Paratha",price:55},
            {item:"Tandoori Aloo Paratha",price:60},
            {item:"Garlic Naan",price:45},
            {item:"Garlic Butter Naan",price:55},
            {item:"Cheese Paratha",price:100},
            {item:"Paneer Paratha",price:70},
            {item:"Chicken Chilli 10 Pcs",price:150},                 /*Non-Veg Chineese Starter*/
            {item:"Chicken Chilli Gravy 8 Pcs",price:150},
            {item:"Chicken Garlic",price:160},
            {item:"Chicken Schezwan",price:160},
            {item:"Chicken Gravy Lollipop",price:170},
            {item:"Chicken Lollipop 6 pcs",price:150},
            {item:"Chicken Crispy",price:150},
            {item:"Chicken Manchurian",price:150},
            {item:"Chicken Fry 8 Pcs",price:150},
            {item:"Chicken 65 Bone 10 Pcs",price:160},
            {item:"Chicken Satay Stick 8 Pcs",price:180},
            {item:"Chicken Fried Rice",price:130},                /*Non-Veg Rice / Noodles*/
            {item:"Chicken Schezwan Fried Rice",price:140},
            {item:"Chicken Triple Schezwan Rice",price:180},
            {item:"Chicken Triple Fried Rice",price:160},
            {item:"Chicken Singapuri Rice",price:150},
            {item:"Chicken Hongkong Rice",price:150},
            {item:"Chicken Manchurian Rice",price:160},
            {item:"Chicken Sanghai Rice",price:160},
            {item:"Chicken Schezwan Noodles",price:140},
            {item:"Chicken Triple Schezwan Noodles",price:160},
            {item:"Chicken Singapuri Noodles",price:150},
            {item:"Chicken Hongkong Noodles",price:150},
            {item:"Chicken Manchurian Noodles",price:160},
            {item:"Chicken Sanghai Noodles",price:160},
            {item:"Chicken Hakka Noodles",price:130},
            {item:"Veg Thali",price:120},                             /*Veg /Non-Veg Thali*/
            {item:"Non-Veg Thali",price:150},
            {item:"Vegetables Biryani",price:800},                   /*We Also Take Party Order*/
            {item:"Paneer Tikka Biryani",price:1000},
            {item:"Paneer Biryani",price:900},
            {item:"Chicken Boneless Biryani",price:1100},
            {item:"Chicken Biryani With Bone",price:1000},
            {item:"Chicken Tikka Biryani Boneless",price:1200},
            {item:"Mutton Biryani",price:1500},
            {item:"Veg Fried Rice",price:110},                    /*Veg Rice /Noodles*/
            {item:"Veg Schezwan Fried Rice",price:120},
            {item:"Veg Triple Schezwan Rice",price:150},
            {item:"Veg Triple Fried Rice",price:140},
            {item:"Veg Singapuri Rice",price:130},
            {item:"Veg Hongkong Rice",price:120},
            {item:"Veg Manchurian Rice",price:150},
            {item:"Veg Sanghai Rice",price:140},
            {item:"Veg Noodles",price:110},
            {item:"Veg Schezwan Noodles",price:130},
            {item:"Veg Triple Noodles",price:160},
            {item:"Veg Singapuri Noodles",price:140},
            {item:"Veg Hongkong Noodles",price:140},
            {item:"Veg Manchurian Noodles",price:160},
            {item:"Sanghai Noodles",price:150},
            {item:"Veg Hakka Noodles",price:120},
            {item:"Egg Masala",price:100},                /*Egg Dishes*/
            {item:"Egg Masala Fry",price:120},
            {item:"Egg Curry",price:100},
            {item:"Egg Fried Rice",price:120},
            {item:"Egg Schezwan Fried Rice",price:130},
            {item:"Egg Triple Schezwan Rice",price:160},
            {item:"Egg Triple Fried Rice",price:150},
            {item:"Egg Singapuri Rice",price:140},
            {item:"Egg Hongkong Rice",price:130},
            {item:"Egg Manchurian Rice",price:160},
            {item:"Egg Sanghai Rice",price:150},
            {item:"Egg Noodles",price:120},
            {item:"Egg Schezwan Noodles",price:140},
            {item:"Egg Triple Noodles",price:170},
            {item:"Egg Singapuri Noodles",price:150},
            {item:"Egg Hongkong Noodles",price:150},
            {item:"Egg Manchurian Noodles",price:170},
            {item:"Egg Sanghai Noodles",price:160},
            {item:"Egg Hakka Noodles",price:130},
            {item:"Paneer Tikka Roll",price:110},             /*Veg roles*/
            {item:"Paneer Malai Tikka Roll",price:120},
            {item:"Paneer Pudina Tikka Roll",price:130},
            {item:"Paneer Achari Tikka Roll",price:140},
            {item:"Paneer Pahadi Tikka Roll",price:150},
            {item:"Chicken Tikka Roll",price:150},                 /*Non Veg Roles*/
            {item:"Chicken Pahadi Tikka Roll",price:160},
            {item:"Chicken Reshmi Tikka Roll",price:170},
            {item:"Chicken Malai Tikka Roll",price:180},
            {item:"Chicken Hydrabadi Kabab Roll",price:190}
        ]
